### ISSUE TITLE
Build fails at target pgxs on gentoo and arch linux

### ISSUE THREAD

**Issue by calimeroteknik** [twain47/Nominatim#453]
I was building Nominatim with the following commands:

```
git clone --recursive https://github.com/twain47/Nominatim.git
cd Nominatim
mkdir build
cd build
cmake ..
make
```
The build fails this way:
```
[ 75%] Linking CXX executable osm2pgsql
[ 75%] Built target osm2pgsql
Scanning dependencies of target nominatim_lib
[ 78%] Running external makefile /usr/lib64/postgresql-9.5/lib64/pgxs/src/makefiles/pgxs.mk
/home/admin/Nominatim/module/Makefile:8: warning: overriding recipe for target 'install'
/usr/lib64/postgresql-9.5/lib64/pgxs/src/makefiles/pgxs.mk:123: warning: ignoring old recipe for target 'install'
make[3]: *** No rule to make target 'nominatim.so', needed by 'all'.  Stop.
module/CMakeFiles/nominatim_lib.dir/build.make:60: recipe for target '../module/dummy' failed
make[2]: *** [../module/dummy] Error 2
CMakeFiles/Makefile2:2073: recipe for target 'module/CMakeFiles/nominatim_lib.dir/all' failed
make[1]: *** [module/CMakeFiles/nominatim_lib.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

The full outputs are here:
gentoo/postgresl9.5: [nominatim-build-pg9.5.txt](https://github.com/twain47/Nominatim/files/277581/nominatim-build-pg9.5.txt)
gentoo/postgresql9.4: [nominatim-build-pg9.4.txt](https://github.com/twain47/Nominatim/files/277583/nominatim-build-pg9.4.txt)
arch/postgresql9.5: [nominatim-build-arch-pg9.5.txt](https://github.com/twain47/Nominatim/files/277590/nominatim-build-arch-pg9.5.txt)

I attempted to add `PG_CONFIG = <full path to pg_config>` at the beginning of `module/Makefile`.
(the full path to pg_config having been obtained through `which pg_config`)
This did not change the above results.

**Comment by lonvia** [comment]
Could you please run `make VERBOSE=1` (after a `make clean`) and post the output?

**Comment by calimeroteknik** [comment]
Sure thing! Here are the build logs with `make VERBOSE=1`:
[nominatim-build-gentoo-362f259.txt](https://github.com/twain47/Nominatim/files/278270/nominatim-build-gentoo-362f259.txt)
[nominatim-build-arch-362f259.txt](https://github.com/twain47/Nominatim/files/278277/nominatim-build-arch-362f259.txt)

**Comment by lonvia** [comment]
Turns out the error message was slightly misleading. It was the source file nominatim.c that make couldn't find. Hopefully all fixed now. Thanks for the detailed infos.

**Comment by parkercoleman** [comment]
I'm still having a similar issue:

[ 87%] Running external makefile /usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk
cd /home/nominatim/Nominatim/build-vagrant/module && PGXS=/usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk PG_CONFIG=/usr/bin/pg_config MODSRCDIR=/home/nominatim/Nominatim/module make -f /home/nominatim/Nominatim/module/Makefile
make[3]: Entering directory `/home/nominatim/Nominatim/build-vagrant/module'
/home/nominatim/Nominatim/module/Makefile:8: warning: overriding recipe for target `install'
/usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk:126: warning: ignoring old recipe for target `install'
make[3]: *** No rule to make target `nominatim.so', needed by `all'.  Stop.
make[3]: Leaving directory `/home/nominatim/Nominatim/build-vagrant/module'
make[2]: *** [../module/dummy] Error 2
make[2]: Leaving directory `/home/nominatim/Nominatim/build-vagrant'
make[1]: *** [module/CMakeFiles/nominatim_lib.dir/all] Error 2
make[1]: Leaving directory `/home/nominatim/Nominatim/build-vagrant'
make: *** [all] Error 2


Looks like its passing in MODSRCDIR, but still failing.  Running Centos and postgres 9.2, any ideas?  Thanks.
